name: Running tests 🚦
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          check-latest: true

      # install dependencies
      - run: npm install

      - name: Run tests
        env:
          CI: true
        run: npm run test
